version: '3'

volumes:
  mongo_data:
    driver: local

services:
  dspfront:
    image: dspfront
    container_name: dsp_dev_dspfront
    volumes:
      - ./../.env:/dspfront/.env
    ports:
      - 5001:5001
    restart: unless-stopped

  nginx:
    image: nginx:1.17.10
    container_name: dsp_dev_nginx
    volumes:
      - ./nginx/nginx-local.conf:/etc/nginx/nginx.conf
      - ./nginx/config:/etc/ssl
    ports:
      - 443:443
    depends_on:
      - dspback

  dspback:
    image: dspback
    container_name: dsp_dev_dspback
    volumes:
      - ./:/dspback
      - ./tests:/tests
    entrypoint: bash dev-entrypoint.sh
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - 5002:5002
    restart: on-failure
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
