version: '3'

services:

  nginx:
    image: nginx:1.17.10
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config:/etc/ssl
    ports:
      - 443:443
    depends_on:
      - backend
      - frontend

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 5001:5001
    restart: on-failure

  backend:
    image: backend
    container_name: backend
    volumes:
      - ./backend:/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 5002:5002
    restart: on-failure

  database:
    image: postgres:latest
    container_name: database
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database

    volumes:
      - ./db-data/:/var/lib/postgresql/data/
