version: '3'

services:

  dspfront:
    image: dspfront
    container_name: dsp_dev_dspfront
    volumes:
      - ./../.env:/dspfront/.env
    ports:
      - 5001:5001
    restart: unless-stopped

  nginx:
    image: nginx:1.17.10
    container_name: dsp_dev_nginx
    volumes:
      - ./nginx/nginx-local.conf:/etc/nginx/nginx.conf
      - ./nginx/config:/etc/ssl
    ports:
      - 443:443
    depends_on:
      - dspback

  dspback:
    image: dspback
    container_name: dsp_dev_dspback
    volumes:
      - ./:/dspback
      - ./tests:/tests
    entrypoint: bash dev-entrypoint.sh
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - 5002:5002
    restart: on-failure
