name: Test Coverage

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build containers
      run: make build

    - name: Startup containers
      run: make up
      
    - name: Install dependencies
      run: make install
      
    - name: Run check
      run: make test-cov
